services:
  main-gateway-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-gateway-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./pom.xml

networks:
  iwa-network:
    driver: bridge