name: Build & Release Service

on:
  push:
    tags:
      - 'v*.*.*'   # e.g. v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME}
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          echo "Building and pushing $IMAGE"
          docker build -t $IMAGE .
          docker push $IMAGE
